### ISSUE TITLE
Cannot connect to servers to download ios 13.1 buildmanifest

### ISSUE THREAD

**Issue by jblsp** [s0uthwest/futurerestore#13]
It could be my problem only. If so I apologize. I am getting error code 22.

**Comment by s0uthwest** [comment]
Write a full log here, please.

**Comment by fr3ns1s** [comment]
Version: 81b98e0425e17250cc83d5badaf9a8cc6399f481 - 245
Libipatcher version: 3159a387584e352f690cca859e013c3a4683f3e8 - 69
Odysseus support: yes
[INFO] 64-bit device detected
futurerestore init done
reading signing ticket 12_4.shsh2 is done
Found device iPhone10,6 d221ap
user specified to use latest signed SEP (WARNING, THIS CAN CAUSE A NON-WORKING RESTORE)
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[TSSC] selecting latest iOS: 13.2
[TSSC] got firmware URL for iOS 13.2 build 17B84
[TSSC] opening Buildmanifest for iPhone10,6_13.2
PKKK??ި?[Error] [LFZP] failed to open URL
[Error] couldn't get buildmanifest of latest firmware
[Error] Fail code=-22
Failed with errorcode=-22

**Comment by s0uthwest** [comment]
Compile build with latest version of libfragmentzip.
