### ISSUE TITLE
Getting this issue when trying to downgrade from 13.2 to 13.1.2 which is signed

### ISSUE THREAD

**Issue by aesthyrica** [s0uthwest/futurerestore#15]
[INFO] 64-bit device detected
futurerestore init done
reading signing ticket /Users/chloee/Documents/Checkm8/7433532640839738_iPhone10,6_d221ap_13.1.2-17A861_27325c8258be46e69d9ee57fa9a8fbc28b873df434e5e702a8b27999551138ae.shsh2 is done
Found device iPhone10,6 d221ap
user specified to use latest signed SEP (WARNING, THIS CAN CAUSE A NON-WORKING RESTORE)
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[TSSC] selecting latest iOS: 13.2
[TSSC] got firmware URL for iOS 13.2 build 17B84
[TSSC] opening Buildmanifest for iPhone10,6_13.2
PKKK??ި?[Error] [LFZP] failed to open URL
[Error] couldn't get buildmanifest of latest firmware
[Error] Fail code=-22
Failed with errorcode=-22
Chloees-MacBook-Pro:~ chloee$

**Comment by DanangCode** [comment]
I am getting the same issue upgrading to 12.1.1 on windows 

[INFO] 64-bit device detected
futurerestore init done
reading signing ticket 5160386035171878_iPad6,4_j128ap_12.1.1-16C50_3ce2b405dbbdda2b0737522a87088e1c8905918a.shsh2 is done
Found device iPad6,4 j128ap
user specified to use latest signed SEP (WARNING, THIS CAN CAUSE A NON-WORKING RESTORE)
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[TSSC] selecting latest iOS: 13.2.2
[TSSC] got firmware URL for iOS 13.2.2 build 17B102
[TSSC] opening Buildmanifest for iPad6,4_13.2.2
PK    ( ( ├  ├╠≥┌  [Error] [LFZP] failed to open URL
[Error] couldn't get buildmanifest of latest firmware
[Error] Fail code=-22
Failed with errorcode=-22

**Comment by DigitalGangster101** [comment]
I also had this error but the work around is to do the manual sep/bb.
