### ISSUE TITLE
[Help] Stuck on “Waiting for Device...”

### ISSUE THREAD

**Issue by Reiza1993** [s0uthwest/futurerestore#4]
So as title said, everything goes well, but after the green screen the Apple Logo came out and my iPhone will stuck there until I hard reset It. 

FutureRestore seems to be not able to connect in Restore Mode, It reaches up to 180 attempts and after fails. 

I m using an MacBook Pro 2011 with MacOS 10.13.3 (High Sierra). I actually heard that FutureRestore is not compatibile with High Sierra or below is that true? 
Following is a txt file with debug log.
[log-2.txt](https://github.com/s0uthwest/futurerestore/files/3051110/log-2.txt)

EDIT: FutureRestore v231, iPhone 6s (iPhone8,1) 11.3.1.

**Comment by s0uthwest** [comment]
futurerestore is compatible with High Sierra.
Use v224 for restoring, it's works for now.

I'll see this problem. Maybe, your cable have problems?

**Comment by lechium** [comment]
Using 231 On macOS 10.13.6, was on a 2017 MBP and it died in the exact same place on an AppleTV 5,3 (4th gen) I don't have the logs anymore unfortunately, but looking at the one in from Reiza and the log looks essentially identical to what i remember, I was actually just checking back here to see if there was a new version or if anyone else had reported the same issue.

**Comment by s0uthwest** [comment]
Fixed.
