### ISSUE TITLE
Unable to successfully restore device 

### ISSUE THREAD

**Issue by winstonlin917** [s0uthwest/futurerestore#5]
Problem as stated in the title. I'm using a Mojave Mac and trying to restore an iPhone SE from 11.4.1 to 12.1.1 using sep and baseband from 12.2 

Log: 

[log.txt](https://github.com/s0uthwest/futurerestore/files/3067542/log.txt)

**Comment by s0uthwest** [comment]
Your problem with SHSH2. It's may be corrupt.
Or your iPhone SE doesn't support FDR connections (on the log).

**Comment by Winston-Lin-9527** [comment]
What does FDR connection mean and how could i possibly solve that? And my shsh blob is fetched from blobsaver which connects to 1conan so maybe that might not be the problem?
