### ISSUE TITLE
FaceID is not available 

### ISSUE THREAD

**Issue by Hwatu** [s0uthwest/futurerestore#8]
My device iPhoneXR 12.0.1 use Futurerestore(v231) to successfully restore to 12.1.1 (beta3), but faceid is not available, is there a way to solve this situation?
Baseband.bbfw version is : 12.3.1
sep.im4p version is : 12.3.1
BuildManifest.plist version is : 12.3.1
help me plz

**Comment by s0uthwest** [comment]
SEP firmware isn't compatible.
