### ISSUE TITLE
Cant compile on Ubuntu 19.04

### ISSUE THREAD

**Issue by 00p513-dev** [s0uthwest/futurerestore#9]
I have been trying to compile futurerestore on Ubuntu MATE 19.04 and it gives me these errors

alex@00p513:~/ios/futurerestore$ ./autogen.sh 
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:31: installing './compile'
configure.ac:15: installing './missing'
futurerestore/Makefile.am: installing './depcomp'
~/ios/futurerestore/external/idevicerestore ~/ios/futurerestore
./autogen.sh: line 18: ./autogen.sh: No such file or directory
~/ios/futurerestore
~/ios/futurerestore/external/img4tool ~/ios/futurerestore
./autogen.sh: line 18: ./autogen.sh: No such file or directory
~/ios/futurerestore
~/ios/futurerestore/external/tsschecker ~/ios/futurerestore
./autogen.sh: line 18: ./autogen.sh: No such file or directory
~/ios/futurerestore
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking whether we need platform-specific build settings... checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for library containing pthread_create... -lpthread
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libplist... yes
checking for libzip... yes
checking for libimobiledevice... yes
checking for libirecovery... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for pkg-config... (cached) /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
Package libipatcher was not found in the pkg-config search path.
Perhaps you should add the directory containing `libipatcher.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libipatcher' found
checking whether to enable WIN32 specific flags... no
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating futurerestore/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
=== configuring in external/idevicerestore (/home/alex/ios/futurerestore/external/idevicerestore)
configure: WARNING: no configuration information is in external/idevicerestore
=== configuring in external/img4tool (/home/alex/ios/futurerestore/external/img4tool)
configure: WARNING: no configuration information is in external/img4tool
=== configuring in external/tsschecker (/home/alex/ios/futurerestore/external/tsschecker)
configure: WARNING: no configuration information is in external/tsschecker

Configuration for futurerestore 1.0:
-------------------------------------------

  Install prefix ..........: /usr/local
  With libipatcher ........: no
  Now type 'make' to build futurerestore 1.0,
  and then 'make install' for installation.

alex@00p513:~/ios/futurerestore$ make
make  all-recursive
make[1]: Entering directory '/home/alex/ios/futurerestore'
Making all in external/idevicerestore
make[2]: Entering directory '/home/alex/ios/futurerestore/external/idevicerestore'
make[2]: *** No rule to make target 'all'. Stop.
make[2]: Leaving directory '/home/alex/ios/futurerestore/external/idevicerestore'
make[1]: *** [Makefile:420: all-recursive] Error 1
make[1]: Leaving directory '/home/alex/ios/futurerestore'
make: *** [Makefile:352: all] Error 2
alex@00p513:~/ios/futurerestore$ make install
Making install in futurerestore
make[1]: Entering directory '/home/alex/ios/futurerestore/futurerestore'
g++ -DHAVE_CONFIG_H -I. -I..    -I/usr/local/include  -I/usr/local/include  -I/usr/local/include -I/usr/include/libusb-1.0 -I../external/tsschecker/external/jssy/jssy -I../external/tsschecker/tsschecker -I../external/img4tool/img4tool -I../external/idevicerestore/src -std=c++11   -g -O2 -MT futurerestore-futurerestore.o -MD -MP -MF .deps/futurerestore-futurerestore.Tpo -c -o futurerestore-futurerestore.o `test -f 'futurerestore.cpp' || echo './'`futurerestore.cpp
In file included from futurerestore.cpp:15:
futurerestore.hpp:16:10: fatal error: idevicerestore.h: No such file or directory
 #include "idevicerestore.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:474: futurerestore-futurerestore.o] Error 1
make[1]: Leaving directory '/home/alex/ios/futurerestore/futurerestore'
make: *** [Makefile:420: install-recursive] Error 1
alex@00p513:~/ios/futurerestore$

**Comment by s0uthwest** [comment]
Use this command to clone repo with git: 
`git clone --recursive https://github.com/s0uthwest/futurerestore`

Submodules isn't copied.
